# title: Yourname's Homepage
# page-top-title: Yourname
# top-section-bg-text: Be what you wanna be
# home-subtitle: Yourname&ensp;|&ensp;上杉绘梨衣
# copyright-text: '&copy; Yourname 2023-2025. All Rights Reserved.'
title: 杨嘉伟的个人主页
page-top-title: 杨嘉伟的个人主页
top-section-bg-text: AI System Acceleration
home-subtitle: 杨嘉伟（Jiawei Yang）
copyright-text: '&copy; 杨嘉伟 2024. All Rights Reserved.'